export const menuSections = [
  {
    title: 'Client & Projects',
    items: [
      { path: '/clients', label: 'Clients', icon: '👥' },
      { path: '/projects', label: 'Projects', icon: '📁' },
      { path: '/billing', label: 'Billing', icon: '🧾' },
      { path: '/payments', label: 'Payments', icon: '💳' },
      { path: '/transactions', label: 'Debit / Credit', icon: '💰' },
    ],
  },
  {
    title: 'Human Resources',
    items: [
      { path: '/employees', label: 'Employees', icon: '👤' },
      { path: '/salaries', label: 'Salary Details', icon: '💵' },
      { path: '/attendance', label: 'Attendance', icon: '📅' },
    ],
  },
];

export const moduleConfigs = {
  clients: {
    title: 'Clients',
    resource: 'clients',
    searchPlaceholder: 'Search by name, email, phone...',
    columns: [
      { key: 'name', label: 'Client Name' },
      { key: 'contact_email', label: 'Email' },
      { key: 'contact_phone', label: 'Phone' },
      { key: 'address', label: 'Address' },
    ],
    fields: [
      { name: 'name', label: 'Client Name', type: 'text', required: true },
      { name: 'contact_email', label: 'Email', type: 'email' },
      { name: 'contact_phone', label: 'Phone', type: 'text' },
      { name: 'address', label: 'Address', type: 'textarea', fullWidth: true },
    ],
  },
  projects: {
    title: 'Projects',
    resource: 'projects',
    searchPlaceholder: 'Search by project, client, status...',
    columns: [
      { key: 'name', label: 'Project Name' },
      { key: 'client_name', label: 'Client' },
      { key: 'start_date', label: 'Start Date' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'details', label: 'Details' },
    ],
    fields: [
      { name: 'client_id', label: 'Client', type: 'select', resource: 'clients', required: true },
      { name: 'name', label: 'Project Name', type: 'text', required: true },
      { name: 'start_date', label: 'Start Date', type: 'date', required: true },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { value: 'active', label: 'Active' },
          { value: 'completed', label: 'Completed' },
          { value: 'on_hold', label: 'On Hold' },
        ],
      },
      { name: 'details', label: 'Project Details', type: 'textarea', fullWidth: true },
    ],
  },
  billing: {
    title: 'Billing Details',
    resource: 'billing',
    searchPlaceholder: 'Search by project, client, amount...',
    columns: [
      { key: 'invoice_number', label: 'Invoice #' },
      { key: 'project_name', label: 'Project' },
      { key: 'client_name', label: 'Client' },
      { key: 'amount', label: 'Amount', type: 'currency' },
      { key: 'billing_date', label: 'Billing Date' },
      { key: 'due_date', label: 'Due Date' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { name: 'project_id', label: 'Project', type: 'select', resource: 'projects', required: true },
      { name: 'invoice_number', label: 'Invoice Number', type: 'text' },
      { name: 'amount', label: 'Amount', type: 'number', required: true, step: '0.01' },
      { name: 'billing_date', label: 'Billing Date', type: 'date', required: true },
      { name: 'due_date', label: 'Due Date', type: 'date' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { value: 'pending', label: 'Pending' },
          { value: 'paid', label: 'Paid' },
          { value: 'overdue', label: 'Overdue' },
        ],
      },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
  },
  payments: {
    title: 'Payment Details',
    resource: 'payments',
    searchPlaceholder: 'Search by project, client, amount...',
    columns: [
      { key: 'project_name', label: 'Project' },
      { key: 'client_name', label: 'Client' },
      { key: 'amount', label: 'Amount', type: 'currency' },
      { key: 'payment_date', label: 'Payment Date' },
      { key: 'payment_method', label: 'Method' },
      { key: 'reference_number', label: 'Reference #' },
    ],
    fields: [
      { name: 'project_id', label: 'Project', type: 'select', resource: 'projects', required: true },
      { name: 'amount', label: 'Amount', type: 'number', required: true, step: '0.01' },
      { name: 'payment_date', label: 'Payment Date', type: 'date', required: true },
      { name: 'payment_method', label: 'Payment Method', type: 'text' },
      { name: 'reference_number', label: 'Reference Number', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
  },
  transactions: {
    title: 'Debit / Credit',
    resource: 'transactions',
    searchPlaceholder: 'Search by project, type, amount...',
    columns: [
      { key: 'type', label: 'Type', type: 'badge' },
      { key: 'project_name', label: 'Project' },
      { key: 'client_name', label: 'Client' },
      { key: 'amount', label: 'Amount', type: 'currency' },
      { key: 'transaction_date', label: 'Date' },
      { key: 'description', label: 'Description' },
    ],
    fields: [
      { name: 'project_id', label: 'Project', type: 'select', resource: 'projects', required: true },
      {
        name: 'type',
        label: 'Type',
        type: 'select',
        required: true,
        options: [
          { value: 'debit', label: 'Debit' },
          { value: 'credit', label: 'Credit' },
        ],
      },
      { name: 'amount', label: 'Amount', type: 'number', required: true, step: '0.01' },
      { name: 'transaction_date', label: 'Transaction Date', type: 'date', required: true },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
  },
  employees: {
    title: 'Employees',
    resource: 'employees',
    searchPlaceholder: 'Search by name, designation, posting...',
    columns: [
      { key: 'name', label: 'Employee Name' },
      { key: 'date_of_joining', label: 'DOJ' },
      { key: 'designation', label: 'Designation' },
      { key: 'place_of_posting', label: 'Place of Posting' },
      { key: 'contact_email', label: 'Email' },
    ],
    fields: [
      { name: 'name', label: 'Employee Name', type: 'text', required: true },
      { name: 'date_of_joining', label: 'Date of Joining', type: 'date', required: true },
      { name: 'designation', label: 'Designation', type: 'text', required: true },
      { name: 'place_of_posting', label: 'Place of Posting', type: 'text' },
      { name: 'contact_email', label: 'Email', type: 'email' },
      { name: 'contact_phone', label: 'Phone', type: 'text' },
    ],
  },
  salaries: {
    title: 'Salary Details',
    resource: 'salaries',
    searchPlaceholder: 'Search by employee, amount...',
    columns: [
      { key: 'employee_name', label: 'Employee' },
      { key: 'designation', label: 'Designation' },
      { key: 'amount', label: 'Salary', type: 'currency' },
      { key: 'effective_from', label: 'Effective From' },
      { key: 'payment_frequency', label: 'Frequency' },
    ],
    fields: [
      { name: 'employee_id', label: 'Employee', type: 'select', resource: 'employees', required: true },
      { name: 'amount', label: 'Salary Amount', type: 'number', required: true, step: '0.01' },
      { name: 'effective_from', label: 'Effective From', type: 'date', required: true },
      {
        name: 'payment_frequency',
        label: 'Payment Frequency',
        type: 'select',
        options: [
          { value: 'monthly', label: 'Monthly' },
          { value: 'biweekly', label: 'Bi-weekly' },
          { value: 'weekly', label: 'Weekly' },
          { value: 'annual', label: 'Annual' },
        ],
      },
      { name: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  attendance: {
    title: 'Attendance',
    resource: 'attendance',
    searchPlaceholder: 'Search by employee, date, status...',
    columns: [
      { key: 'employee_name', label: 'Employee' },
      { key: 'designation', label: 'Designation' },
      { key: 'attendance_date', label: 'Date' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'check_in', label: 'Check In' },
      { key: 'check_out', label: 'Check Out' },
    ],
    fields: [
      { name: 'employee_id', label: 'Employee', type: 'select', resource: 'employees', required: true },
      { name: 'attendance_date', label: 'Date', type: 'date', required: true },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { value: 'present', label: 'Present' },
          { value: 'absent', label: 'Absent' },
          { value: 'half_day', label: 'Half Day' },
          { value: 'leave', label: 'Leave' },
        ],
      },
      { name: 'check_in', label: 'Check In', type: 'time' },
      { name: 'check_out', label: 'Check Out', type: 'time' },
      { name: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
};
